### ISSUE TITLE
Can't list files

### ISSUE THREAD

**Issue by sphess** [sgratzl/slack_cleaner2#36]
Hello - perhaps I just don't have the correct syntax, but I can't list files - I just get an error.

I've added all of the oauth scope permissions in the Slack app that I can think of.

Thanks!

**To Reproduce**
from slack_cleaner2 import SlackCleaner
s = SlackCleaner("<TOKEN>", sleep_for=1)
for file in s.files(channel='general'):
	print(file.name)

**Output**
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x000002657FE43E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x000002657FE43E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x000002657FE43E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x000002657FE43E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x000002657FE43E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x000002657FE43E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x000002657FE43E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x000002657FE43E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x000002657FE43E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x000002657FE43E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x000002657FE43E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x000002657FE43E50>: unknown error occurred: fetch_members_failed
Traceback (most recent call last):
  File "CleanSlack.py", line 11, in <module>
    for file in s.files(user="*",before="20200401",channel='random'):
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\slack_cleaner2\model.py", line 559, in list
    for sfile in files:
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\slack_cleaner2\model.py", line 905, in safe_paginated_api
    page, meta = self.safe_api(list_page, [attr, "response_metadata"], [[], dict()], scopes, method)
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\slack_cleaner2\model.py", line 867, in safe_api
    res = fun()
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\slack_cleaner2\model.py", line 901, in list_page
    return fun(dict(limit=limit))
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\slack_cleaner2\model.py", line 557, in <lambda>
    files = slack.safe_paginated_api(lambda kw: api.list(user=user, ts_from=after, ts_to=before, types=types, channel=channel, **kw), "files", ["files:read"], "files.list")
TypeError: list() got an unexpected keyword argument 'limit'

- Version: 2.4.2
- Python Version:  3.8

**Comment by sgratzl** [comment]
should be fixed with v2.4.3

**Comment by sphess** [comment]
Hello,
I updated - the errors are different, but still fails:
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x0000024BCA834E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x0000024BCA834E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x0000024BCA834E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x0000024BCA834E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x0000024BCA834E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x0000024BCA834E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x0000024BCA834E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x0000024BCA834E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x0000024BCA834E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x0000024BCA834E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x0000024BCA834E50>: unknown error occurred: fetch_members_failed
<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x0000024BCA834E50>: unknown error occurred: fetch_members_failed
files.list: unknown error occurred: internal_error

**Comment by rcarmo** [comment]
Same here. Just tried it.
